project:
  type: website
  output-dir: _site
  
resources:
  - "data/*"
  - "images/*"

website:
  title: ""
  description: "Data visualisation is the best"
  site-url: https://graphplotchartdatastory.io
  repo-url: https://github.com/visibledata/graph-plot-chart-chart-data-story
  # google-analytics: "XX"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@charliejhadley"
    site: "@charliejhadley"
    card-style: "summary_large_image"
  navbar:
    # background: "#4464AD"
    background: "#2b2b2b"
    color: "white"
    title: false
    left: 
      - icon: house
        text: "Home"
        file: index.qmd
      - href: graph.qmd
      - href: plots-and-charts.qmd
      - href: data-story.qmd
      - icon: bi-arrows-move
        text: "Interactivity & Dashboards"
        file: interactivity-and-dashboards.qmd
    right:
      - href: blog.qmd
      - href: podcast.qmd
      - text: "Articles"
        menu:
          - text: "Interactive data visualisations"
            href: interactive-dataviz.qmd
          - text: "Dashboards"
            href: dashboards.qmd

format:
  html:
    theme: default
    css: styles.scss
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    # include-in-header:
    #   - includes.html
    highlight-style: tango
