project:
  type: website
  output-dir: docs
  
resources:
  - "data/*"
  - "images/*"

website:
  title: ""
  description: "Data visualisation is the best"
  site-url: https://graphplotchartdatastory.io
  repo-url: https://github.com/visibledata/graph-plot-chart-chart-data-story
  # google-analytics: "XX"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@charliejhadley"
    site: "@charliejhadley"
    card-style: "summary_large_image"
  navbar:
    pinned: true
    # background: "#4464AD"
    # background: "#2b2b2b"
    color: "white"
    title: false
    left: 
      # - icon: house
      #   text: "Home"
      #   file: index.qmd
      - icon: tools
        text: "Workshops"
        menu:
          - text: "R"
            href: workshops_r.qmd
          - text: "Data Storytelling"
            href: workshops_data-storytelling.qmd
          - text: "About our workshops"
            href: workshops_overview.qm
      - text: "Articles"
        menu:
          - text: "Blog"
            href: blog.qmd
          - text: "Dashboards"
            href: dashboards.qmd
      - icon: broadcast-pin
        href: podcast.qmd
      - icon: chat-left-quote-fill
        text: "Contact us"
        href: consulting-and-coaching.qmd
    right:
      - icon: patch-question-fill
        text: "Graph, Plot, Chart or Data Story?"
        href: what-it-it.qmd
  page-footer:
    left: |
      GPCDS is run by Charlotte Hadley
      <br>Please get in touch!
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Quarto Blog RSS

format:
  html:
    theme: default
    css: styles.scss
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    # include-in-header:
    #   - includes.html
    highlight-style: tango
