project:
  type: website
  output-dir: docs
  
resources:
  - "data/*"
  - "images/*"

website:
  title: "Graph | Plot | Chart | Data Story"
  description: "Data visualisation is the best"
  site-url: https://graphplotchartdatastory.io
  repo-url: https://github.com/visibledata/graph-plot-chart-chart-data-story
  # google-analytics: "XX"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@charliejhadley"
    site: "@charliejhadley"
    card-style: "summary_large_image"
  navbar:
    search: false
    pinned: true
    # background: "#4464AD"
    # background: "#2b2b2b"
    color: "white"
    title: GPCDS
    left: 
      # - icon: house
      #   text: "Home"
      #   file: index.qmd
      - text: "<i class='fa-solid fa-brush'></i> Workshops"
        href: workshops_overview.qmd
      - text: "<i class='fa-solid fa-mountain-sun'></i> Bootcamps"
        href: bootcamps.qmd
    right:
      - text: "Coaching"
        href: coaching-and-consulting.qmd
      - text: "Articles"
        menu:
          - text: "Our blog"
            href: blog.qmd
          - text: "---"
          - text: "Graph? Plot? Or Chart...?"
            icon: patch-question-fill
            href: what-it-it.qmd
      - text: "About us"
        href: about.qmd
  page-footer:
    left: |
      Graph | Plot | Chart | Data Story
      <br>hello@gpcds.com
      <br/><a href='data-ethics_t-and-cs.html'>Data Ethics and T&Cs</a>.
    center:
      - text: "<i class='fa-solid fa-brush'></i> Workshops"
        href: workshops_overview.qmd
      - text: "<i class='fa-solid fa-mountain-sun'></i> Bootcamps"
        href: bootcamps.qmd
      - text: "<i class='fa-solid fa-lightbulb'></i> Coaching"
        href: coaching-and-consulting.qmd
    right:
      - icon: linkedin
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
  sidebar:
    - id: id-workshop
      title: "GPCDS Workshops"
      style: "docked"
      background: light
      contents:
        - text: "<span style='color:red;'>About</span> our workshops"
        - text: "INFO"
          href: INFO.qmd
        - text: "------"
        - text: "About our trainer"
          href: Other.qmd
format:
  html:
    theme: [default, styles.scss]
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    # include-in-header:
    #   - includes.html
    highlight-style: tango
    include-in-header:
      - includes.html